### ISSUE TITLE
The demo live is not working anymore 

### ISSUE THREAD

**Issue by jackey** [fura-protocol/fura-api-quickswap#1]
https://demo.furadao.org/subgraph/polygon/quickswap 
it redirects that to https://fura.org/

**Comment by furaprotocol** [comment]
it should be ok now, please visit again  

official site: https://info.quickswap.exchange  

our demo site: https://staging.fura.org/quickswap  

and  https://demo.furadao.org/subgraph/polygon/quickswap also jumps to it

**Comment by timon0305** [comment]
https://api.fura.org/subgraphs/name/quickswap

Instead of this api, which endpoint can I use? @furaprotocol @jackey
